version: '1'

networks:
  custom-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.0.0/16

services:

  consul:
    container_name: consul
    image: hashicorp/consul
    ports:
      - "8500:8500"

  db-recensioni:
    container_name: db-recensioni
    image: mysql:latest
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: mysql-password
      MYSQL_DATABASE: recensioni

  db-connessioni:
    container_name: db-connessioni
    image: mysql:latest
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: mysql-password
      MYSQL_DATABASE: connessioni

  db-recensioni-seguite:
    container_name: db-recensioni-seguite
    image: mysql:latest
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: mysql-password
      MYSQL_DATABASE: recensioni-seguite

  recensioni:
    image: openjdk:11-jdk
    working_dir: /app
    volumes:
      - ./recensioni/build/libs/recensioni.jar:/app/recensioni.jar
    command: java -Xms64m -Xmx128m -jar recensioni.jar
    depends_on:
      - "consul"
      - "db-recensioni"

  connessioni:
    image: openjdk:11-jdk
    working_dir: /app
    volumes:
      - ./connessioni/build/libs/connessioni.jar:/app/connessioni.jar
    command: java -Xms64m -Xmx128m -jar connessioni.jar
    depends_on:
      - "consul"
      - "db-connessioni"

  recensioni-seguite:
    image: openjdk:11-jdk
    working_dir: /app
    volumes:
      - ./recensioni-seguite/build/libs/recensioni-seguite.jar:/app/recensioni-seguite.jar
    command: java -Xms64m -Xmx128m -jar recensioni-seguite.jar
    depends_on:
      - "consul"

  api-gateway:
    image: openjdk:11-jdk
    working_dir: /app
    volumes:
      - ./api-gateway/build/libs/api-gateway.jar:/app/api-gateway.jar
    command: java -Xms64m -Xmx128m -jar api-gateway.jar
    depends_on:
      - "consul"
    networks:
      default:
      custom-network: 
        ipv4_address: 10.10.10.10

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"

  kafka:
    image: bitnami/kafka:latest
    environment:
      KAFKA_BROKER_ID: 1
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "recensioni:1:1, connessioni:1:1"
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
